inetd.c: 'n' undeclared
This fixes incomplete renaming of `n` in https://github.com/vda-linux/busybox_mirror/commit/ad88be9e7ea4ae74b5b012d75e5b92ff12ca273d

With CONFIG_FEATURE_INETD_RPC :
```
networking/inetd.c: In function 'reread_config_file':
networking/inetd.c:1046:23: error: 'n' undeclared (first use in this function)
     sep->se_rpcprog = n;
                       ^
networking/inetd.c:1046:23: note: each undeclared identifier is reported only once for each function it appears in
```